# Generated by Django 5.0.7 on 2024-07-25 09:07

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(default='Golakganj', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AWC_Code', models.IntegerField()),
                ('AWC_Name', models.CharField(max_length=100)),
                ('AWW_Name', models.CharField(max_length=100)),
                ('AWW_Phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('AWH_Name', models.CharField(max_length=100)),
                ('AWH_Phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('AWC_Address', models.TextField()),
                ('Building_Type', models.CharField(choices=[('Govt Building', 'Govt Building'), ('Private Building', 'Private Building')], max_length=20)),
                ('AWC_Image', models.ImageField(blank=True, null=True, upload_to='AWC_images/')),
                ('Drinking_Water_Facility', models.BooleanField(default=False)),
                ('Toilet_Facility', models.BooleanField(default=False)),
                ('Electricity_Avaiable', models.BooleanField(default=False)),
                ('Kitchen_Garden_Available', models.BooleanField(default=False)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='users.sector')),
            ],
        ),
    ]
