# Generated by Django 5.0.7 on 2024-07-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_admition'),
    ]

    operations = [
        migrations.AddField(
            model_name='admition',
            name='email',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
    ]
